### ISSUE TITLE
No module named 'einsteinpy.coordinates'

### ISSUE THREAD

**Issue by DhruvKumarPHY** [einsteinpy/einsteinpy#631]
🐞 **Problem**
I am constantly facing this issue, please help me to fix it.

{ No module named 'einsteinpy.coordinates' }

This is the complete code -- 
import numpy as np
import einsteinpy
from einsteinpy.coordinates import CartesianDifferential, CartesianCoordinates
from einsteinpy.metric import Kerr
from einsteinpy.plotting import StaticGeodesicPlotter

# Define the properties of the Kerr naked singularity
M = 1.0  # Mass of the singularity in solar masses
a = 0.9 * M  # Spin of the singularity in units of mass
r0 = 2.0 * M  # Initial radial distance of the test particle

# Calculate the properties of the singularity
metric = Kerr(M=M, a=a,coords= CartesianDifferential)
horizon = metric.event_horizon()
ergosphere = metric.ergosphere()

# Simulate the behavior of a test particle in the vicinity of the singularity
theta, phi = np.pi / 2, 0  # Initial polar and azimuthal angles of the particle
rp = 1.5 * horizon.radius  # Periapsis distance of the particle
ecc = 0.8  # Eccentricity of the particle's orbit
inc = np.pi / 4  # Inclination angle of the particle's orbit

plotter = StaticGeodesicPlotter(metric=metric, coords="Schwarzschild", axtype="3d", dark=True)

plotter.plot_trajectory(
    r=r0, th=theta, ph=phi, rp=rp, ecc=ecc, inc=inc,
    color="red", lw=2.5, label="Test Particle Trajectory"
)

plotter.plot_surface(
    ergosphere.spherical[0], ergosphere.spherical[1],
    color="#2EE6C0", alpha=0.3, label="Ergosphere"
)

plotter.plot_surface(
    horizon.spherical[0], horizon.spherical[1],
    color="#A569BD", alpha=0.3, label="Event Horizon"
)

plotter.show()

**Comment by JeS24** [comment]
Hey @DhruvKumarPHY. Which version of EinsteinPy are you using? Can you run `pip list` in the command line / terminal / command prompt and paste the output here?

**Comment by Joseph-CSI1430** [comment]
I am having a similar issue:

import numpy as np
 
from einsteinpy.coordinates.utils import four_position, stacked_vec
from einsteinpy.geodesic import Geodesic
from einsteinpy.metric import Schwarzschild
 
M = 6e24  # Mass
t = 0.  # Coordinate Time (has no effect in this case, as Schwarzschild metric is static)
x_vec = np.array([130.0, np.pi / 2, -np.pi / 8])  # 3-Position of test particle
v_vec = np.array([0.0, 0.0, 1900.0])  # 3-Velocity of test particle
 
ms_cov = Schwarzschild(M=M) # Schwarzschild Metric Object
x_4vec = four_position(t, x_vec) # Getting Position 4-Vector
ms_cov_mat = ms_cov.metric_covariant(x_4vec) # Calculating Schwarzschild Metric at x_4vec
init_vec = stacked_vec(ms_cov_mat, t, x_vec, v_vec, time_like=True) # Contains 4-Pos and 4-Vel
 
# Calculating Geodesic
geod = Geodesic(metric=ms_cov, init_vec=init_vec, end_lambda=0.002, step_size=5e-8)
# Getting a descriptive summary on geod
print(geod)

I ran this code in Blender's Python API (Blender 3.5, python version 3.10.8) and got this error: 

Python: Traceback (most recent call last):
  File "C:\Users\ifean\OneDrive\Desktop\Physics Stuff\EinsteinPy Test Simulation.blend\EinsteinPy Tester", line 4, in <module>
ImportError: cannot import name 'four_position' from 'einsteinpy.coordinates.utils' (C:\Users\ifean\AppData\Roaming\Python\Python310\site-packages\einsteinpy\coordinates\utils.py)

**Comment by JeS24** [comment]
@Joseph-CSI1430 @DhruvKumarPHY Which version of EinsteinPy are you using? If you run `pip show einsteinpy` in the terminal / command prompt / Powershell, it should show you the version.

EinsteinPy 0.4.0 doesn't have `four_position` or `stacked_vec`. If you are using 0.4.0 (which is on PyPI and hence, installed using `pip`), please use the up-to-date documentation from here: https://docs.einsteinpy.org/en/latest/ (Note the `latest/` at the end of the link). In particular, here's an example for calculating timelike geodesics, similar to what your code is doing, using 0.4.0 - https://docs.einsteinpy.org/en/latest/jupyter.html and you can find more such examples here - https://docs.einsteinpy.org/en/latest/jupyter.html.

**Comment by Joseph-CSI1430** [comment]
Thanks, and yes I am using version 0.4.0. I specifically would like to simulate timelike null geodesics around a Schwarzschild black hole.

**Comment by Joseph-CSI1430** [comment]
One more question: how can I access the cartesian coordinates of the geodesic path?

**Comment by JeS24** [comment]
@Joseph-CSI1430 It is in Cartesian by default. You can access it via `geod.trajectory`, which is a tuple of 2 numpy arrays - `(timesteps, 3d_position)`, as shown here:
![image](https://github.com/einsteinpy/einsteinpy/assets/31299799/f91f5c2a-2677-4e14-91c9-588fb32aa2f7)

**Comment by JeS24** [comment]
`geod` being the geodesic object described at the aforementioned [link](https://docs.einsteinpy.org/en/latest/user_guide.html#geodesic-module).

**Comment by Joseph-CSI1430** [comment]
Thanks, but I am still having some issues:

import bpy
import numpy as np
from einsteinpy.geodesic import Timelike


# Define the geodesic parameters
position = [40., np.pi / 2, 0.]
momentum = [0., 0., 3.83405]
a = 0.  # Spin = 0 for a Schwarzschild black hole
steps = 5500  # Number of steps to be taken by the solver
delta = 1  # Step size

# Generate the geodesic
geod = Timelike(
    metric="Schwarzschild",
    metric_params=(a,),
    position=position,
    momentum=momentum,
    steps=steps,
    delta=delta,
    suppress_warnings=True,
    return_cartesian=True
)

# Access the trajectory
path = geod.trajectory
trajectory = path[2]

# Convert the trajectory to an array
path = np.array(trajectory)

I am trying to use this code to convert the trajectory into an array so that I can then use it to plot a nurbs curve in Blender (it's fine if you are not familiar with blender). But the error I have right now is this:

Python: Traceback (most recent call last):
  File "C:\Users\ifean\OneDrive\Desktop\Physics Stuff\Schwarzschild EPR Paradox.blend\EinsteinPy Tester", line 27, in <module>
IndexError: tuple index out of range

**Comment by JeS24** [comment]
In python, arrays are 0-indexed. So, valid indices for `path` are `0` for the timesteps & `1` for the trajectory. Changing `trajectory = path[2]` to `path[1]` should work. And `path = np.array(trajectory)` isn't needed, since it is already a numpy array.

Also, I was incorrect in stating that `geod.trajectory[1]` had 3D positions. It is actually a `Nx8` array with N timesteps and 8 columns holding 4D position and 4D momentum values. For your case, you'll only need the 3D position values. So, you can slice the array like so:
```py
path = geod.trajectory[1] # (t, x, y, z, pt, px, py, pz)
path3d = path[:, [1, 2, 3, 0]] # : -> for all rows, [1, 2, 3, 0] -> new index order (x, y, z, t)

# Now you can pass path3d to a `spline` object in blender
```

Since, we are veering off topic from the opened issue, I'd suggest creating a Discussion question about this at https://github.com/einsteinpy/einsteinpy/discussions/new, in case you need more help.

**Comment by JeS24** [comment]
Closing this issue due to inactivity.
