### ISSUE TITLE
Won't install with PIP

### ISSUE THREAD

**Issue by David-OConnor** [einsteinpy/einsteinpy#632]
```python
Collecting numba!=0.49.0,>=0.46
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\david\AppData\Local\Temp\pip-install-kjd8wjro\numba_17e5f45e8dbf4b2f850a0efb94b9ffae\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\david\AppData\Local\Temp\pip-install-kjd8wjro\numba_17e5f45e8dbf4b2f850a0efb94b9ffae\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install -
```

**Comment by JeS24** [comment]
Hello @David-OConnor, thanks for opening the issue. As this line in the traceback states;
> RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.

`numba`, which is a dependency of EinsteinPy, does not yet support Python 3.11. It is due to add support soon however - https://github.com/numba/numba/issues/8841. Till that is done, can you try installing EinsteinPy on Python 3.10 or lower (till Python 3.8)? That should work without issues. Also, for the documentation, please follow this link: https://docs.einsteinpy.org/en/latest/.

**Comment by David-OConnor** [comment]
Thanks for the info! Working on 3.10 as you said. Sounds like the play is wait for Numba.

**Comment by JeS24** [comment]
Numba added support for Python 3.11 -> https://github.com/numba/numba/releases/tag/0.57.0. This issue should be resolved now.
